//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOVELAVIDBEntities : DbContext
    {
        public SOVELAVIDBEntities()
            : base("name=SOVELAVIDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_COMMUNE> tbl_COMMUNE { get; set; }
        public virtual DbSet<tbl_COU> tbl_COU { get; set; }
        public virtual DbSet<tbl_COU_ACTIVATION_HISTORY> tbl_COU_ACTIVATION_HISTORY { get; set; }
        public virtual DbSet<tbl_COUC> tbl_COUC { get; set; }
        public virtual DbSet<tbl_COUD> tbl_COUD { get; set; }
        public virtual DbSet<tbl_COUN> tbl_COUN { get; set; }
        public virtual DbSet<tbl_DEGAT> tbl_DEGAT { get; set; }
        public virtual DbSet<tbl_DEPARTEMENT> tbl_DEPARTEMENT { get; set; }
        public virtual DbSet<tbl_EVENEMENT> tbl_EVENEMENT { get; set; }
        public virtual DbSet<tbl_EVENEMENT_COMMUNE> tbl_EVENEMENT_COMMUNE { get; set; }
        public virtual DbSet<tbl_INSTITUTION> tbl_INSTITUTION { get; set; }
        public virtual DbSet<tbl_LAYER> tbl_LAYER { get; set; }
        public virtual DbSet<tbl_LAYER_CATEGORY> tbl_LAYER_CATEGORY { get; set; }
        public virtual DbSet<tbl_LAYER_TYPE> tbl_LAYER_TYPE { get; set; }
        public virtual DbSet<tbl_MEMBRE> tbl_MEMBRE { get; set; }
        public virtual DbSet<tbl_MENACE> tbl_MENACE { get; set; }
        public virtual DbSet<tbl_NIVEAU_DEGAT_MATERIELS> tbl_NIVEAU_DEGAT_MATERIELS { get; set; }
        public virtual DbSet<tbl_POI> tbl_POI { get; set; }
        public virtual DbSet<tbl_POI_TYPE> tbl_POI_TYPE { get; set; }
        public virtual DbSet<tbl_PRIORITE_EVENEMENT> tbl_PRIORITE_EVENEMENT { get; set; }
        public virtual DbSet<tbl_REPONSE> tbl_REPONSE { get; set; }
        public virtual DbSet<tbl_RESSOURCE> tbl_RESSOURCE { get; set; }
        public virtual DbSet<tbl_RESSOURCE_TYPE> tbl_RESSOURCE_TYPE { get; set; }
        public virtual DbSet<tbl_ROLE> tbl_ROLE { get; set; }
        public virtual DbSet<tbl_SEXE> tbl_SEXE { get; set; }
        public virtual DbSet<tbl_STATUT_EVENEMENT> tbl_STATUT_EVENEMENT { get; set; }
        public virtual DbSet<tbl_TYPE_MENACE> tbl_TYPE_MENACE { get; set; }
        public virtual DbSet<tbl_USER> tbl_USER { get; set; }
        public virtual DbSet<tbl_USER_ROLE_COU> tbl_USER_ROLE_COU { get; set; }
        public virtual DbSet<tbl_VULNERABILITE> tbl_VULNERABILITE { get; set; }
        public virtual DbSet<tbl_VULNERABILITE_HISTORIQUE> tbl_VULNERABILITE_HISTORIQUE { get; set; }
        public virtual DbSet<tbl_VULNERABILITE_NIVEAU> tbl_VULNERABILITE_NIVEAU { get; set; }
    }
}
