//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOVELAVIDBEntities : DbContext
    {
        public SOVELAVIDBEntities()
            : base("name=SOVELAVIDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ALERTE> tbl_ALERTE { get; set; }
        public virtual DbSet<tbl_CARACTERISTIQUE_MENACE> tbl_CARACTERISTIQUE_MENACE { get; set; }
        public virtual DbSet<tbl_COLLECTIVITE_TERRITORIALE> tbl_COLLECTIVITE_TERRITORIALE { get; set; }
        public virtual DbSet<tbl_COMMUNE> tbl_COMMUNE { get; set; }
        public virtual DbSet<tbl_CONTACT> tbl_CONTACT { get; set; }
        public virtual DbSet<tbl_COU> tbl_COU { get; set; }
        public virtual DbSet<tbl_COU_ACTIVATION_HISTORY> tbl_COU_ACTIVATION_HISTORY { get; set; }
        public virtual DbSet<tbl_DEPARTEMENT> tbl_DEPARTEMENT { get; set; }
        public virtual DbSet<tbl_DONNEE> tbl_DONNEE { get; set; }
        public virtual DbSet<tbl_EVENEMENT> tbl_EVENEMENT { get; set; }
        public virtual DbSet<tbl_EVENEMENT_COLLECTIVITE_TERRITORIALE> tbl_EVENEMENT_COLLECTIVITE_TERRITORIALE { get; set; }
        public virtual DbSet<tbl_EVENEMENT_TYPE_DEGAT> tbl_EVENEMENT_TYPE_DEGAT { get; set; }
        public virtual DbSet<tbl_FIABILITE_SOURCE> tbl_FIABILITE_SOURCE { get; set; }
        public virtual DbSet<tbl_INSTITUTION> tbl_INSTITUTION { get; set; }
        public virtual DbSet<tbl_LAYER> tbl_LAYER { get; set; }
        public virtual DbSet<tbl_LAYER_CATEGORY> tbl_LAYER_CATEGORY { get; set; }
        public virtual DbSet<tbl_LAYER_TYPE> tbl_LAYER_TYPE { get; set; }
        public virtual DbSet<tbl_MEMBRE> tbl_MEMBRE { get; set; }
        public virtual DbSet<tbl_MENACE> tbl_MENACE { get; set; }
        public virtual DbSet<tbl_MENACE_INTENSITE> tbl_MENACE_INTENSITE { get; set; }
        public virtual DbSet<tbl_NIVEAU> tbl_NIVEAU { get; set; }
        public virtual DbSet<tbl_NIVEAU_ALERTE> tbl_NIVEAU_ALERTE { get; set; }
        public virtual DbSet<tbl_PERIODE> tbl_PERIODE { get; set; }
        public virtual DbSet<tbl_PHOTO> tbl_PHOTO { get; set; }
        public virtual DbSet<tbl_POI> tbl_POI { get; set; }
        public virtual DbSet<tbl_POI_TYPE> tbl_POI_TYPE { get; set; }
        public virtual DbSet<tbl_PRIORITE_DONNEE> tbl_PRIORITE_DONNEE { get; set; }
        public virtual DbSet<tbl_PRIORITE_EVENEMENT> tbl_PRIORITE_EVENEMENT { get; set; }
        public virtual DbSet<tbl_REPONSE> tbl_REPONSE { get; set; }
        public virtual DbSet<tbl_RESSOURCE> tbl_RESSOURCE { get; set; }
        public virtual DbSet<tbl_RESSOURCE_TYPE> tbl_RESSOURCE_TYPE { get; set; }
        public virtual DbSet<tbl_RESSOURCES_AFFECTEES> tbl_RESSOURCES_AFFECTEES { get; set; }
        public virtual DbSet<tbl_ROLE> tbl_ROLE { get; set; }
        public virtual DbSet<tbl_SECTION_COMMUNALE> tbl_SECTION_COMMUNALE { get; set; }
        public virtual DbSet<tbl_SEXE> tbl_SEXE { get; set; }
        public virtual DbSet<tbl_TAG> tbl_TAG { get; set; }
        public virtual DbSet<tbl_TYPE_DEGAT> tbl_TYPE_DEGAT { get; set; }
        public virtual DbSet<tbl_TYPE_EVENEMENT> tbl_TYPE_EVENEMENT { get; set; }
        public virtual DbSet<tbl_TYPE_INSTITUTION> tbl_TYPE_INSTITUTION { get; set; }
        public virtual DbSet<tbl_TYPE_MENACE> tbl_TYPE_MENACE { get; set; }
        public virtual DbSet<tbl_TYPE_REPONSE> tbl_TYPE_REPONSE { get; set; }
        public virtual DbSet<tbl_UNITE_REFERENCE> tbl_UNITE_REFERENCE { get; set; }
        public virtual DbSet<tbl_USER> tbl_USER { get; set; }
        public virtual DbSet<tbl_USER_ROLE_COU> tbl_USER_ROLE_COU { get; set; }
        public virtual DbSet<tbl_VULNERABILITE> tbl_VULNERABILITE { get; set; }
        public virtual DbSet<tbl_VULNERABILITE_HISTORIQUE> tbl_VULNERABILITE_HISTORIQUE { get; set; }
        public virtual DbSet<tbl_VULNERABILITE_NIVEAU> tbl_VULNERABILITE_NIVEAU { get; set; }
        public virtual DbSet<tbl_POI_MENACE_VULNERABILITE> tbl_POI_MENACE_VULNERABILITE { get; set; }
    }
}
