//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RESSOURCE
    {
        public int id { get; set; }
        public string nom { get; set; }
        public int typeRessourceId { get; set; }
        public int qteDisponible { get; set; }
        public int qteNecessaire { get; set; }
        public int communeId { get; set; }
    
        public virtual tbl_COMMUNE tbl_COMMUNE { get; set; }
        public virtual tbl_RESSOURCE_TYPE tbl_RESSOURCE_TYPE { get; set; }
    }
}
