//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ALERTE
    {
        public int id { get; set; }
        public int niveauAlerteId { get; set; }
        public System.DateTime alerteStartDate { get; set; }
        public Nullable<System.DateTime> alerteEndDate { get; set; }
        public bool isCurrentAlerteState { get; set; }
        public Nullable<int> couId { get; set; }
        public int startBy { get; set; }
        public int endBy { get; set; }
    
        public virtual tbl_COU tbl_COU { get; set; }
        public virtual tbl_NIVEAU_ALERTE tbl_NIVEAU_ALERTE { get; set; }
        public virtual tbl_USER tbl_USER { get; set; }
        public virtual tbl_USER tbl_USER1 { get; set; }
    }
}
