//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_USER()
        {
            this.tbl_USER_ROLE_COU = new HashSet<tbl_USER_ROLE_COU>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public string passwordHash { get; set; }
        public string salt { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<System.DateTime> lastOnline { get; set; }
        public string telephone { get; set; }
        public int sexeId { get; set; }
    
        public virtual tbl_SEXE tbl_SEXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_USER_ROLE_COU> tbl_USER_ROLE_COU { get; set; }
    }
}
