//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EVENEMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_EVENEMENT()
        {
            this.tbl_EVENEMENT_COMMUNE = new HashSet<tbl_EVENEMENT_COMMUNE>();
        }
    
        public int id { get; set; }
        public int statutId { get; set; }
        public int priorite { get; set; }
        public int degatId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EVENEMENT_COMMUNE> tbl_EVENEMENT_COMMUNE { get; set; }
        public virtual tbl_PRIORITE_EVENEMENT tbl_PRIORITE_EVENEMENT { get; set; }
        public virtual tbl_STATUT_EVENEMENT tbl_STATUT_EVENEMENT { get; set; }
    }
}
