//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ACCESSIBILITE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ACCESSIBILITE()
        {
            this.tbl_ACCESS_HISTORIQUE = new HashSet<tbl_ACCESS_HISTORIQUE>();
        }
    
        public int id { get; set; }
        public int niveauId { get; set; }
        public int moyenId { get; set; }
        public int collectiviteId { get; set; }
        public System.DateTime StartDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ACCESS_HISTORIQUE> tbl_ACCESS_HISTORIQUE { get; set; }
        public virtual tbl_COLLECTIVITE_TERRITORIALE tbl_COLLECTIVITE_TERRITORIALE { get; set; }
        public virtual tbl_MOYEN_ACCES tbl_MOYEN_ACCES { get; set; }
        public virtual tbl_NIVEAU_ACCES tbl_NIVEAU_ACCES { get; set; }
    }
}
