//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RESSOURCES_AFFECTEES
    {
        public int id { get; set; }
        public int qteAffectee { get; set; }
        public int reponseId { get; set; }
        public int sourceId { get; set; }
        public int degatID { get; set; }
    
        public virtual tbl_EVENEMENT_TYPE_DEGAT tbl_EVENEMENT_TYPE_DEGAT { get; set; }
        public virtual tbl_REPONSE tbl_REPONSE { get; set; }
        public virtual tbl_RESSOURCE tbl_RESSOURCE { get; set; }
    }
}
