//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_COUD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_COUD()
        {
            this.tbl_COUC = new HashSet<tbl_COUC>();
        }
    
        public int id { get; set; }
        public int departementId { get; set; }
        public Nullable<int> counId { get; set; }
    
        public virtual tbl_COU tbl_COU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_COUC> tbl_COUC { get; set; }
        public virtual tbl_COUN tbl_COUN { get; set; }
        public virtual tbl_DEPARTEMENT tbl_DEPARTEMENT { get; set; }
    }
}
