//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_INSTITUTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_INSTITUTION()
        {
            this.tbl_MEMBRE = new HashSet<tbl_MEMBRE>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int type { get; set; }
        public int contactId { get; set; }
    
        public virtual tbl_CONTACT tbl_CONTACT { get; set; }
        public virtual tbl_TYPE_INSTITUTION tbl_TYPE_INSTITUTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MEMBRE> tbl_MEMBRE { get; set; }
    }
}
