//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_POI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_POI()
        {
            this.tbl_POI_MENACE_VULNERABILITE = new HashSet<tbl_POI_MENACE_VULNERABILITE>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int poiType { get; set; }
        public string addresse { get; set; }
        public int communeId { get; set; }
        public bool isArisque { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_POI_MENACE_VULNERABILITE> tbl_POI_MENACE_VULNERABILITE { get; set; }
        public virtual tbl_POI_TYPE tbl_POI_TYPE { get; set; }
    }
}
