//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_COLLECTIVITE_TERRITORIALE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_COLLECTIVITE_TERRITORIALE()
        {
            this.tbl_ACCESSIBILITE = new HashSet<tbl_ACCESSIBILITE>();
            this.tbl_COU = new HashSet<tbl_COU>();
            this.tbl_EVENEMENT_COLLECTIVITE_TERRITORIALE = new HashSet<tbl_EVENEMENT_COLLECTIVITE_TERRITORIALE>();
            this.tbl_EVENEMENT_TYPE_DEGAT = new HashSet<tbl_EVENEMENT_TYPE_DEGAT>();
            this.tbl_RESSOURCE = new HashSet<tbl_RESSOURCE>();
            this.tbl_VULNERABILITE = new HashSet<tbl_VULNERABILITE>();
        }
    
        public int id { get; set; }
        public int niveauId { get; set; }
        public Nullable<int> deptId { get; set; }
        public Nullable<int> communeId { get; set; }
        public Nullable<int> sectId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ACCESSIBILITE> tbl_ACCESSIBILITE { get; set; }
        public virtual tbl_COMMUNE tbl_COMMUNE { get; set; }
        public virtual tbl_DEPARTEMENT tbl_DEPARTEMENT { get; set; }
        public virtual tbl_NIVEAU tbl_NIVEAU { get; set; }
        public virtual tbl_SECTION_COMMUNALE tbl_SECTION_COMMUNALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_COU> tbl_COU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EVENEMENT_COLLECTIVITE_TERRITORIALE> tbl_EVENEMENT_COLLECTIVITE_TERRITORIALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EVENEMENT_TYPE_DEGAT> tbl_EVENEMENT_TYPE_DEGAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RESSOURCE> tbl_RESSOURCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VULNERABILITE> tbl_VULNERABILITE { get; set; }
    }
}
