//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DEGAT
    {
        public int id { get; set; }
        public int qteBlesse { get; set; }
        public int qteMorts { get; set; }
        public Nullable<int> niveauDegatsMateriels { get; set; }
    
        public virtual tbl_NIVEAU_DEGAT_MATERIELS tbl_NIVEAU_DEGAT_MATERIELS { get; set; }
    }
}
