//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CONTACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CONTACT()
        {
            this.tbl_INSTITUTION = new HashSet<tbl_INSTITUTION>();
            this.tbl_MEMBRE = new HashSet<tbl_MEMBRE>();
            this.tbl_USER = new HashSet<tbl_USER>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string telephoneSecondaire { get; set; }
        public string adresse { get; set; }
        public string skypeID { get; set; }
        public string facebookProfile { get; set; }
        public string website { get; set; }
        public string instagram { get; set; }
        public string twitter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_INSTITUTION> tbl_INSTITUTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MEMBRE> tbl_MEMBRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_USER> tbl_USER { get; set; }
    }
}
