//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_COMMUNE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_COMMUNE()
        {
            this.tbl_COLLECTIVITE_TERRITORIALE = new HashSet<tbl_COLLECTIVITE_TERRITORIALE>();
            this.tbl_SECTION_COMMUNALE = new HashSet<tbl_SECTION_COMMUNALE>();
            this.tbl_VULNERABILITE_HISTORIQUE = new HashSet<tbl_VULNERABILITE_HISTORIQUE>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int departementId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_COLLECTIVITE_TERRITORIALE> tbl_COLLECTIVITE_TERRITORIALE { get; set; }
        public virtual tbl_DEPARTEMENT tbl_DEPARTEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SECTION_COMMUNALE> tbl_SECTION_COMMUNALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VULNERABILITE_HISTORIQUE> tbl_VULNERABILITE_HISTORIQUE { get; set; }
    }
}
