//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_USER_ROLE_COU
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int couId { get; set; }
        public int roleId { get; set; }
    
        public virtual tbl_COU tbl_COU { get; set; }
        public virtual tbl_ROLE tbl_ROLE { get; set; }
        public virtual tbl_USER tbl_USER { get; set; }
    }
}
