//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_COU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_COU()
        {
            this.tbl_COU_ACTIVATION_HISTORY = new HashSet<tbl_COU_ACTIVATION_HISTORY>();
            this.tbl_USER_ROLE_COU = new HashSet<tbl_USER_ROLE_COU>();
        }
    
        public int id { get; set; }
        public bool isActive { get; set; }
        public double lattitude { get; set; }
        public double longitude { get; set; }
        public Nullable<System.DateTime> activationDate { get; set; }
        public string activationMotif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_COU_ACTIVATION_HISTORY> tbl_COU_ACTIVATION_HISTORY { get; set; }
        public virtual tbl_COUC tbl_COUC { get; set; }
        public virtual tbl_COUD tbl_COUD { get; set; }
        public virtual tbl_COUN tbl_COUN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_USER_ROLE_COU> tbl_USER_ROLE_COU { get; set; }
    }
}
