//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MENACE_INTENSITE
    {
        public int id { get; set; }
        public int menaceId { get; set; }
        public int caracteristiqueId { get; set; }
        public double valeurCaracteristique { get; set; }
        public Nullable<int> periodeId { get; set; }
    
        public virtual tbl_CARACTERISTIQUE_MENACE tbl_CARACTERISTIQUE_MENACE { get; set; }
        public virtual tbl_MENACE tbl_MENACE { get; set; }
    }
}
