//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_COU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_COU()
        {
            this.tbl_ALERTE = new HashSet<tbl_ALERTE>();
            this.tbl_COU_ACTIVATION_HISTORY = new HashSet<tbl_COU_ACTIVATION_HISTORY>();
            this.tbl_MEMBRE = new HashSet<tbl_MEMBRE>();
            this.tbl_USER_ROLE_COU = new HashSet<tbl_USER_ROLE_COU>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public bool isActive { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public Nullable<System.DateTime> lastCloseDate { get; set; }
        public string activationMotif { get; set; }
        public Nullable<System.DateTime> lastActiveDate { get; set; }
        public Nullable<int> activatedBy { get; set; }
        public Nullable<int> closeBy { get; set; }
        public int collectiviteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ALERTE> tbl_ALERTE { get; set; }
        public virtual tbl_COLLECTIVITE_TERRITORIALE tbl_COLLECTIVITE_TERRITORIALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_COU_ACTIVATION_HISTORY> tbl_COU_ACTIVATION_HISTORY { get; set; }
        public virtual tbl_USER tbl_USER { get; set; }
        public virtual tbl_USER tbl_USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MEMBRE> tbl_MEMBRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_USER_ROLE_COU> tbl_USER_ROLE_COU { get; set; }
    }
}
