//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MEMBRE
    {
        public int id { get; set; }
        public int institutionId { get; set; }
        public int couId { get; set; }
        public int contactId { get; set; }
    
        public virtual tbl_CONTACT tbl_CONTACT { get; set; }
        public virtual tbl_COU tbl_COU { get; set; }
        public virtual tbl_INSTITUTION tbl_INSTITUTION { get; set; }
    }
}
