//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EVENEMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_EVENEMENT()
        {
            this.tbl_EVENEMENT_COLLECTIVITE_TERRITORIALE = new HashSet<tbl_EVENEMENT_COLLECTIVITE_TERRITORIALE>();
            this.tbl_EVENEMENT_TYPE_DEGAT = new HashSet<tbl_EVENEMENT_TYPE_DEGAT>();
        }
    
        public int id { get; set; }
        public int priorite { get; set; }
        public string nom { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public double lattitude { get; set; }
        public double longittude { get; set; }
        public int menace { get; set; }
        public int type { get; set; }
        public Nullable<int> degatId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EVENEMENT_COLLECTIVITE_TERRITORIALE> tbl_EVENEMENT_COLLECTIVITE_TERRITORIALE { get; set; }
        public virtual tbl_MENACE tbl_MENACE { get; set; }
        public virtual tbl_PRIORITE_EVENEMENT tbl_PRIORITE_EVENEMENT { get; set; }
        public virtual tbl_TYPE_EVENEMENT tbl_TYPE_EVENEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EVENEMENT_TYPE_DEGAT> tbl_EVENEMENT_TYPE_DEGAT { get; set; }
    }
}
