//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CARACTERISTIQUE_MENACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CARACTERISTIQUE_MENACE()
        {
            this.tbl_MENACE_INTENSITE = new HashSet<tbl_MENACE_INTENSITE>();
        }
    
        public int id { get; set; }
        public string nom { get; set; }
        public int uniteReferenceId { get; set; }
    
        public virtual tbl_UNITE_REFERENCE tbl_UNITE_REFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MENACE_INTENSITE> tbl_MENACE_INTENSITE { get; set; }
    }
}
