//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EVENEMENT_COMMUNE
    {
        public int id { get; set; }
        public int communeId { get; set; }
        public int evenementId { get; set; }
    
        public virtual tbl_COMMUNE tbl_COMMUNE { get; set; }
        public virtual tbl_EVENEMENT tbl_EVENEMENT { get; set; }
    }
}
